version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: todo
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
    links:
      - pg
  pg:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-todo-db.sql:/docker-entrypoint-initdb.d/init-todo-db.sql
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: todo

volumes:
  postgres:
